spring.application.name=ProjectManagement
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER}
spring.security.oauth2.resourceserver.jwt.audiences=${JWT_AUD}

management.endpoints.web.exposure.include=*
management.endpoints.health.show-details=always
#logging.file.name=./logs/spring-boot.log
logging.level.root=INFO
logging.pattern.level=%5p [%X{apiName}] [%X{userId}]

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true